### PR TITLE
Remove cache & make distro more specific

### PR DESCRIPTION
**Pull request by eagleoflqj**
I see .sass-cache in .gitignore, but it seems that the folder was tracked by git before gitignore declares the exclusion, so I remove that.
Then I add some information about arch, but the installation command may not cover all dependencies needed. Maybe some packages are pre-installed by my distro. Hope somebody who gets dependency failure could complement that.

### CODE REVIEW

**Comment by eagleoflqj** [comment]
#11

**Comment by xarkes** [comment]
Hello, thanks for the contribution!
In fact, the website is mostly generated thanks to the [docs folder](https://github.com/radareorg/cutter/tree/master/docs) on Cutter repository.
You can directly edit the `.rst` file from this link, https://github.com/radareorg/cutter/blob/master/docs/source/building.rst by clicking on the top right pencil :)

Also if you feel like these instructions could have been better explained somewhere else, feel free to make a PR or let us know!

**Comment by ITAYC0HEN** [comment]
Exactly :) Similar changes, different repo

**Comment by eagleoflqj** [comment]
Cool, editing html was annoying.
Should I make another PR to delete .sass-cache, then?

**Comment by xarkes** [comment]
The website that is served online is on the branch `gh-pages` https://github.com/radareorg/cutter.re/tree/gh-pages.
The `.sass-cache` folder does not appear on this branch, however maybe one of the script in Cutter repository could be modified to remove the folder if existant. I'm not sure if that's relevant, up to you :)

**Pull request closed without merging**
